"""add models

Revision ID: 777d0e150730
Revises: b5a7086f296c
Create Date: 2023-05-15 22:43:47.677209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "777d0e150730"
down_revision = "b5a7086f296c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("isbn", sa.String(), nullable=False),
        sa.Column("publisher", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_id"), table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
